//
// Autogenerated by Thrift Compiler (0.21.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import thrift = require('thrift');
import Thrift = thrift.Thrift;
import Q = thrift.Q;
import Int64 = require('node-int64');


declare class User {
  public id: number;
  public name: string;

    constructor(args?: { id: number; name: string; });
}

declare class GetUserRequest {
  public userId: number;

    constructor(args?: { userId: number; });
}

declare class GetUserResponse {
  public user: User;

    constructor(args?: { user: User; });
}
